# Generated by Django 3.1.3 on 2020-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201126_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True, null=True),
        ),
    ]
